[2024-12-18T19:27:58.343+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-18T19:27:58.380+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fintech_etl_pipeline.load_to_db manual__2024-12-18T19:27:12.612495+00:00 [queued]>
[2024-12-18T19:27:58.411+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fintech_etl_pipeline.load_to_db manual__2024-12-18T19:27:12.612495+00:00 [queued]>
[2024-12-18T19:27:58.412+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-18T19:27:58.452+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_to_db> on 2024-12-18 19:27:12.612495+00:00
[2024-12-18T19:27:58.479+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=130) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-18T19:27:58.479+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fintech_etl_pipeline', 'load_to_db', 'manual__2024-12-18T19:27:12.612495+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/fintech_dag.py', '--cfg-path', '/tmp/tmpbhu821jo']
[2024-12-18T19:27:58.485+0000] {standard_task_runner.py:72} INFO - Started process 143 to run task
[2024-12-18T19:27:58.485+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask load_to_db
[2024-12-18T19:27:58.604+0000] {task_command.py:467} INFO - Running <TaskInstance: fintech_etl_pipeline.load_to_db manual__2024-12-18T19:27:12.612495+00:00 [running]> on host 3053742118dc
[2024-12-18T19:27:58.781+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineering_team' AIRFLOW_CTX_DAG_ID='fintech_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-12-18T19:27:12.612495+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-18T19:27:12.612495+00:00'
[2024-12-18T19:27:58.785+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-18T19:27:59.468+0000] {logging_mixin.py:190} INFO - Connected to Database
[2024-12-18T19:28:00.443+0000] {logging_mixin.py:190} INFO - Writing transformed dataset to database
[2024-12-18T19:28:25.601+0000] {logging_mixin.py:190} INFO - Done writing to database
[2024-12-18T19:28:25.615+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-18T19:28:25.665+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-18T19:28:25.669+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fintech_etl_pipeline, task_id=load_to_db, run_id=manual__2024-12-18T19:27:12.612495+00:00, execution_date=20241218T192712, start_date=20241218T192758, end_date=20241218T192825
[2024-12-18T19:28:25.853+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-18T19:28:26.001+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-18T19:28:26.010+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
